blank_issues_enabled: false
contact_links:
  - name: EmuELEC Forum
    url: https://emuelec.org
    about: If you have a regular/general questions, please use the forum instead of a GH issue.
  - name: Discord
    url: https://discord.com/invite/cbgtJTu
    about: If you have a regular/general question, please use discord instead of a GH issue.
